full_ignitions_file:
 class: File
 location: ./data/yosemite_ignitions_firesize_100ac.csv
rx_burn_units_file:
 class: File
 location: ./data/rx_burn.tar.gz
burned_area_file:
 class: File
 location: ./data/burned_area.tar.gz
building_damage_file:
 class: File
 location: ./data/building_damage.tar.gz
intensity_file:
 class: File
 location: ./data/intensity.tar.gz
habitat_damage_file:
 class: File
 location: ./data/habitat_damage.tar.gz
values_table_file:
 class: File
 location: ./data/values_table.csv
prevention_table_file:
 class: File
 location: ./data/prevention_table.csv
initial_hazard_file:
 class: File
 location: ./data/initial_hazard.tif
merged_hazard_file:
 class: File
 location: ./data/merged_hazard.tif  
alpha: 0.1
budget: 15
